DXCC_COUNTRIES = [
    "Afghanistan",
    "Agalega & St. Brandon",
    "Alaska",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andaman & Nicobar",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua & Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Ascension Island",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Azores",
    "Bahamas",
    "Bahrain",
    "Baker & Howland Islands",
    "Balearic Islands",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia-Herzegovina",
    "Botswana",
    "Bouvet",
    "Brazil",
    "British Virgin Islands",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Canary Islands",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chatham Islands",
    "Chile",
    "China",
    "Christmas Island",
    "Clipperton Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Crete",
    "Croatia",
    "Crozet Island",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Cyprus SBA",
    "Czech Republic",
    "Democratic Republic of Congo",
    "Denmark",
    "Desecheo Island",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "DPR Korea",
    "Ducie Island",
    "East Malaysia",
    "Easter Island",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "European Russia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French West Indies",
    "Gabon",
    "Galapagos Islands",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Glorioso Islands",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guantanamo Bay",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Hawaii",
    "Heard Island",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Jan Mayen",
    "Japan",
    "Jersey",
    "Jordan",
    "Juan de Nova, Europa",
    "Kazakhstan",
    "Kenya",
    "Kerguelen Islands",
    "Kermadec Islands",
    "Kingdom of Eswatini",
    "Kiribati",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lao Peoples Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Lord Howe Island",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Madeira Islands",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malpelo Island",
    "Malta",
    "Mariana Islands",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Midway Island",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles (Old)",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Cook Islands",
    "North Macedonia",
    "Northern Ireland",
    "Northern Mariana Islands",
    "Norway",
    "Ogasawara",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Island",
    "Poland",
    "Portugal",
    "Prince Edward & Marion Islands",
    "Puerto Rico",
    "Qatar",
    "Republic of Kosovo",
    "Republic of South Africa",
    "Reunion",
    "Rodrigues Island",
    "Romania",
    "Rotuma",
    "Rwanda",
    "Saba & St. Eustatius",
    "Saint Barthelemy",
    "Saint Kitts & Nevis",
    "Saint Lucia",
    "Sint Maarten",
    "Samoa",
    "San Andres & Providencia",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Barths",
    "Slovak Republic",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Cook Islands",
    "South Georgia Island",
    "South Orkney Islands",
    "South Sandwich Islands",
    "South Shetland Islands",
    "Spain",
    "Spratly Islands",
    "Sri Lanka",
    "St. Helena",
    "St. Pierre & Miquelon",
    "Sudan",
    "Suriname",
    "Svalbard",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tokelau Islands",
    "Tonga",
    "Trinidad & Tobago",
    "Tristan da Cunha & Gough",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks & Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United States",
    "Uruguay",
    "US Virgin Islands",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Wake Island",
    "Wallis & Futuna",
    "Wales",
    "West Malaysia",
    "Western Sahara",
    "Willis Island",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
