# app/dxcc_list.py
"""
DXCC entity lists.

You should keep:
- ACTIVE_DXCC   -> all currently active ARRL entities (target: 340)
- DELETED_DXCC  -> all deleted entities
- DXCC_ALL      -> ACTIVE_DXCC + DELETED_DXCC

The code uses:
- ACTIVE_DXCC when "include deleted" is OFF
- DXCC_ALL      when "include deleted" is ON
"""

# TODO: Replace/extend these with your full lists.
# For now I've put some sample entries so the app runs;
# you can paste your full list here.

ACTIVE_DXCC = [
    "1A0 Sovereign Military Order of Malta",
    "3A Monaco",
    "3B8 Mauritius",
    "3B9 Rodrigues Island",
    "3C Equatorial Guinea",
    "3C0 Annobon",
    "3D2 Fiji",
    "3D2 Rotuma",
    "3DA Eswatini (Swaziland)",
    "3V Tunisia",
    "3W Vietnam",
    "3X Guinea",
    "3Y Bouvet",
    "4J Azerbaijan",
    "4L Georgia",
    "4O Montenegro",
    "4S Sri Lanka",
    "4U1UN United Nations HQ",
    "4W Timor-Leste",
    "4X Israel",
    "5A Libya",
    "5B Cyprus",
    "5H Tanzania",
    "5N Nigeria",
    "5R Madagascar",
    "5T Mauritania",
    "5U Niger",
    "5V Togo",
    "5W Samoa",
    "5X Uganda",
    "5Z Kenya",
    "6Y Jamaica",
    "7P Lesotho",
    "7Q Malawi",
    "7X Algeria",
    "8P Barbados",
    "8R Guyana",
    "9A Croatia",
    "9G Ghana",
    "9H Malta",
    "9J Zambia",
    "9K Kuwait",
    "9L Sierra Leone",
    "9M2 West Malaysia",
    "9M6 East Malaysia",
    "9N Nepal",
    "9U Burundi",
    "9V Singapore",
    "9X Rwanda",
    "9Y Trinidad & Tobago",
    "A2 Botswana",
    "A3 Tonga",
    "A4 Oman",
    "A5 Bhutan",
    "A6 United Arab Emirates",
    "A7 Qatar",
    "A9 Bahrain",
    "AP Pakistan",
    "BV Taiwan",
    "BY China",
    "C2 Nauru",
    "C3 Andorra",
    "C5 The Gambia",
    "C6A Bahamas",
    "CE Chile",
    "CE0 Easter Island",
    "CM Cuba",
    "CN Morocco",
    "CP Bolivia",
    "CT Portugal",
    "CT3 Madeira",
    "CU Azores",
    "CX Uruguay",
    "D2 Angola",
    "D4 Cape Verde",
    "D6 Comoros",
    "DL Germany",
    "DU Philippines",
    "E3 Eritrea",
    "E4 Palestine",
    "E5 North Cook Islands",
    "E5 South Cook Islands",
    "E6 Niue",
    "E7 Bosnia & Herzegovina",
    "EA Spain",
    "EA6 Balearic Islands",
    "EA8 Canary Islands",
    "EA9 Ceuta & Melilla",
    "EI Ireland",
    "EK Armenia",
    "EL Liberia",
    "EP Iran",
    "ER Moldova",
    "ES Estonia",
    "ET Ethiopia",
    "EU Belarus",
    "EX Kyrgyzstan",
    "EY Tajikistan",
    "EZ Turkmenistan",
    "F France",
    "FG Guadeloupe",
    "FH Mayotte",
    "FJ Saint Barthelemy",
    "FK New Caledonia",
    "FM Martinique",
    "FO French Polynesia",
    "FP St. Pierre & Miquelon",
    "FR Reunion",
    "FS Saint Martin",
    "FY French Guiana",
    "G England",
    "GD Isle of Man",
    "GI Northern Ireland",
    "GJ Jersey",
    "GM Scotland",
    "GU Guernsey",
    "GW Wales",
    "H4 Solomon Islands",
    "HA Hungary",
    "HB9 Switzerland",
    "HC Ecuador",
    "HC8 Galapagos",
    "HH Haiti",
    "HI Dominican Republic",
    "HK Colombia",
    "HL South Korea",
    "HP Panama",
    "HR Honduras",
    "HS Thailand",
    "HV Vatican City",
    "HZ Saudi Arabia",
    "I Italy",
    "IS0 Sardinia",
    "J2 Djibouti",
    "J3 Grenada",
    "J5 Guinea-Bissau",
    "J6 Saint Lucia",
    "J7 Dominica",
    "J8 Saint Vincent",
    "JA Japan",
    "JT Mongolia",
    "JW Svalbard",
    "JX Jan Mayen",
    "JY Jordan",
    "K United States",
    "KG4 Guantanamo Bay",
    "KH0 Northern Mariana Islands",
    "KH2 Guam",
    "KH6 Hawaii",
    "KH8 American Samoa",
    "KH9 Wake Island",
    "KL Alaska",
    "KP1 Navassa",
    "KP2 US Virgin Islands",
    "KP4 Puerto Rico",
    "LA Norway",
    "LU Argentina",
    "LX Luxembourg",
    "LY Lithuania",
    "LZ Bulgaria",
    "OA Peru",
    "OD Lebanon",
    "OE Austria",
    "OH Finland",
    "OH0 Aland Islands",
    "OJ0 Market Reef",
    "OK Czech Republic",
    "OM Slovakia",
    "ON Belgium",
    "OX Greenland",
    "OY Faroe Islands",
    "OZ Denmark",
    "P2 Papua New Guinea",
    "P4 Aruba",
    "P5 North Korea",
    "PA Netherlands",
    "PJ2 Curacao",
    "PJ4 Bonaire",
    "PJ5 Saba & St. Eustatius",
    "PJ7 Sint Maarten",
    "PP Brazil",
    "PZ Suriname",
    "S0 Western Sahara",
    "S2 Bangladesh",
    "S5 Slovenia",
    "S7 Seychelles",
    "S9 Sao Tome & Principe",
    "SM Sweden",
    "SP Poland",
    "ST Sudan",
    "SU Egypt",
    "SV Greece",
    "SV5 Dodecanese",
    "SV9 Crete",
    "T2 Tuvalu",
    "T5 Somalia",
    "T7 San Marino",
    "T8 Palau",
    "TA Turkey",
    "TF Iceland",
    "TG Guatemala",
    "TI Costa Rica",
    "TI9 Cocos Island",
    "TJ Cameroon",
    "TK Corsica",
    "TL Central African Republic",
    "TN Congo",
    "TR Gabon",
    "TT Chad",
    "TU Ivory Coast",
    "TY Benin",
    "TZ Mali",
    "UA Russia (European)",
    "UA0 Russia (Asiatic)",
    "UK Uzbekistan",
    "UN Kazakhstan",
    "UR Ukraine",
    "V2 Antigua & Barbuda",
    "V3 Belize",
    "V4 St. Kitts & Nevis",
    "V5 Namibia",
    "V6 Micronesia",
    "V7 Marshall Islands",
    "V8 Brunei",
    "VE Canada",
    "VK Australia",
    "VK0 Heard Island",
    "VK0 Macquarie Island",
    "VK9X Christmas Island",
    "VK9L Lord Howe Island",
    "VK9N Norfolk Island",
    "VK9W Willis Island",
    "VK9Z Cocos/Keeling",
    "VP2E Anguilla",
    "VP2M Montserrat",
    "VP2V British Virgin Islands",
    "VP5 Turks & Caicos",
    "VP6 Pitcairn Island",
    "VP8 Falkland Islands",
    "VP8 South Georgia",
    "VP8 South Sandwich",
    "VP8 Antarctic Peninsula",
    "VP9 Bermuda",
    "VQ9 Chagos Islands",
    "VR Hong Kong",
    "VU India",
    "VU4 Andaman & Nicobar",
    "VU7 Lakshadweep",
    "XE Mexico",
    "XF4 Revillagigedo",
    "XT Burkina Faso",
    "XU Cambodia",
    "XW Laos",
    "XX9 Macau",
    "XZ Myanmar",
    "YA Afghanistan",
    "YB Indonesia",
    "YI Iraq",
    "YK Syria",
    "YL Latvia",
    "YN Nicaragua",
    "YO Romania",
    "YS El Salvador",
    "YT Serbia",
    "YU Serbia",
    "YV Venezuela",
    "Z2 Zimbabwe",
    "Z3 North Macedonia",
    "Z8 South Sudan",
    "ZA Albania",
    "ZB2 Gibraltar",
    "ZC4 UK Bases on Cyprus",
    "ZD7 St. Helena",
    "ZD8 Ascension Island",
    "ZD9 Tristan da Cunha",
    "ZF Cayman Islands",
    "ZK3 Tokelau",
    "ZL New Zealand",
    "ZL7 Chatham Islands",
    "ZL8 Kermadec Islands",
    "ZL9 Auckland & Campbell",
    "ZM New Zealand",
    "ZP Paraguay",
    "ZS South Africa",
    "ZS8 Prince Edward & Marion",
]

# These are examples; extend/modify to match ARRL’s full deleted list.
DELETED_DXCC = [
    "East Germany",
    "West Germany",
    "Czechoslovakia",
    "USSR",
    "Yugoslavia",
    "Netherlands Antilles",
    "Rhodesia",
    "Panama Canal Zone",
    "Canton Island",
    "Portuguese Timor",
    "Portuguese India",
    "South Vietnam",
    "North Vietnam",
    "French Equatorial Africa",
    "French West Africa",
    "British Somaliland",
    "French Somaliland",
    "Saar",
    "Tannu Tuva",
    "New Hebrides",
    "British Honduras",
    "Gilbert & Ellice Islands",
    "Bechuanaland",
    "Basutoland",
    "Nyasaland",
    "Zanzibar",
    "Tanganyika",
    "Sikkim",
    "Ruanda-Urundi",
    "Belgian Congo",
    "French Oceania",
    "Malaya",
    "Straits Settlements",
    "Sarawak",
    "North Borneo",
    "Canal Zone",
    "Swan Islands",
    "Navassa (old)",
    "Brunei (old)",
    "French Indo-China",
    "Congo Free State",
]

DXCC_ALL = ACTIVE_DXCC + DELETED_DXCC
ACTIVE_DXCC_SET = set(ACTIVE_DXCC)
DELETED_DXCC_SET = set(DELETED_DXCC)
DXCC_ALL_SET = set(DXCC_ALL)
